//
// Created by jimmy on 2016/11/26.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_sq_fastblur_FastBlurUtils */

#ifndef _Included_org_sq_fastblur_FastBlurUtils
#define _Included_org_sq_fastblur_FastBlurUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_sq_fastblur_FastBlurUtils
 * Method:    blurPixels
 * Signature: ([IIII)V
 */
JNIEXPORT void JNICALL
        Java_org_sq_fastblur_FastBlurUtils_blurPixels
        (JNIEnv
         *, jclass, jintArray, jint, jint, jint);

/*
 * Class:     org_sq_fastblur_FastBlurUtils
 * Method:    blurBitmap
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL
        Java_org_sq_fastblur_FastBlurUtils_blurBitmap
        (JNIEnv
         *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
